#!/bin/bash
usage () {
    cat <<HELP_USAGE

    $0  [OPTIONS] ([ImageFileName] | --) [arguments]
    
    Requires the squeak vm installed and CUISPATH to point to the
    Cuis-Smalltalk-Dev base repository.
    
    OPTIONS are the squeak command options.

HELP_USAGE
}
#Patches
generateFile() {
	cat > "$1" <<"__PATCH"
'From Cuis 5.0 of 7 November 2016 [latest update: #3665] on 7 October 2019 at 7:32:57 pm'!
'Description This package contains support for dependencies injection via an appropriate environment variable, and offloading of version numbering in packages to an external tool.'!
!provides: '0cuis' 1 1!
!FeatureRequirement methodsFor: 'private' stamp: 'lo 10/7/2019 15:54:52'!
placesToLookForPackagesDo: aBlock
		"Look into local and environment defined paths to search for packages"
		
	pathName ifNotNil: [ aBlock value: pathName asFileEntry parent ].
	(self primEnvironmentAt: #CUISPATH)
		ifNotNil: [:aString |
			aString asDirectoryEntry allDirectoriesDo: aBlock ].
	(self primEnvironmentAt: #CUISPACKAGESPATH)
		ifNotNil: [:aString |
			(aString findTokens: ':')
				do: [:each |
					| d |
					d := each asDirectoryEntry.
					aBlock value: d.
					d allDirectoriesDo: aBlock ] ].
! !

!FeatureRequirement methodsFor: 'private' stamp: 'lo 10/7/2019 19:32:45'!
primEnvironmentAt: aSymbol
	"Answer the environment string at aSymbol in the OS process environment list.
	This returns a string or nil."

	<primitive: 'primitiveEnvironmentAtSymbol' module: 'UnixOSProcessPlugin'>
	^ nil! !
__PATCH
}

if [[ -z "$CUISPATH" ]]
then
	echo >&2 "CUISPATH not set"
	usage
	exit 1
fi
ARGS=()
	#options without arguments
options1="-nomixer -vtlock -vtswitch -compositioninput -fullscreen -fullscreenDirect\
-headless -iconic -lazy -mapdelbs -nointl -notitle -noxdnd -swapbtn -xasync -xshm -help\
-timephases -noevents -nohandlers -pollpip -checkpluginwrites -version -warnpid -tracestores\
-reportheadroom -logscavenge -blockonerror -blockonwarn -exitonwarn -notimer -headless\
-nodisplay -nomixer -nosound -quartz "
	#options with one argument
options2="-display -maxoldspace -cogminjumps -cogmaxlits -tracestores -codesize -pathenc\
-plugins -textenc -stackpages -leakcheck -eden -breakmnu -breaksel -mmap -memory\
-encoding -xicfont -optmod -ldtoms -title -glxdebug -display -cmdmod -browserWindow\
-msproto -msdev -kbmap -fbdev"
	#options with two arguments
options3="-browserPipes"

	#Note: CUISPATH indicates where to find the cuis images and changes...

#Iterate over the arguments, shifting them and adding them to the ARGS array
while test $# -gt 0
do
	if [[ "${options1}" == *"$1"* ]]
	then
		ARGS+=("$1")
		shift 1
		continue
	elif [[ "${options2}" == *"$1"* ]]
	then
		ARGS+=("$1" "$2")
		shift 2
		continue
	elif [[ "${options3}" == *"1"* ]]
	then
		ARGS+=("$1" "$2" "$3")
		shift 3
		continue
	elif [[ "--" == "$1" ]]
	then
		break
	elif [[ ${1::1} == "-" ]]
	then
		echo "Unknown option $1."
		usage
		exit 3
	else
		if [ ! -f "$1" ]
		then
			cp ${CUISPATH}/Cuis5.0-????.image "$1" || exit 2
			chmod +w "$1" || exit 2
			cp ${CUISPATH}/Cuis5.0-????.changes "${1%\.image}.changes" || exit 2
			chmod +w "${1%\.image}.changes" || exit 2
			cp -n ${CUISPATH}/CuisV5.sources "$(dirname \"$1\")/CuisV5.sources"
			generateFile "$(dirname \"$1\")/0cuis.pck.st"
			squeak -headless "$1" -r"$(dirname \"$1\")/0cuis.pck.st" -d"Smalltalk snapshot: true andQuit: true"
		fi
		break
	fi
done
command -v squeak >/dev/null 2>&1 || \
	{ echo >&2 "I require squeak but it's not installed."; usage; exit 1; }
exec squeak ${ARGS[@]} "$@"